### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#52]
- [x]  Item Materials
- [x]  Block Materials
- [x]  Welten entladen
- [ ] setSkin() (mit Input Stream, path, URL, etc.)
- [x] removeAllEffects()
- [x]  Problem mit pmmp und nukkit Welten
- [x]  Play a sound for a player only
- [ ]  send Title
- [ ]  add breaking API
- [x] EntityLiving add teleport
- [ ]  BossBar
- [x] player.getDirectionVector();
- [ ]  Floating Text Particle
- [ ]  Item Frames (Wegen den Maps, auf welchen Frames verbaut sind)
- [ ] Clear Inventory soll Schild und Crafting Field mit leeren
- [ ]  PlayerToggleFlightEvent
- [ ] NPCs 
- [ ]  Farbige Lederrüstung
- [ ]  Elytra + isGliding()
- [ ]  getDefaultWorld
----------------------
Nice to have
- [x]  player.getX()...
- [ ] broadcastMessage()
- [ ] InteractEvent: getItem Shortcut
- [ ] Inventory: remove (int) 
- [ ] Inventory: setItemInHand(ItemStack)

---------------------------------
Bugs:
- [x] Man schwimmt in Wasser, wenn man nach vorne drückt, automatisch nach oben?

**Comment by LucGamesYT** [comment]
Was auch cool wäre:
- [ ] setNameTag(); / getNameTag();
- [ ] Eine Methode womit man alle Chests zB bekommen kann
- [ ] Eigenen WorldGenerator
- [ ] setFireTicks();
- [ ] entity.getKiller();

**Comment by BexiPE** [comment]
[] Events fehlen teilweise
[] Scheduler fehlen teileweise

**Comment by Janmm14** [comment]
(Ich würde ja eher extradaten zu maps speichern anstatt alle kisten abzufragen)

**Comment by geNAZt** [comment]
Asking the server for a list of specific blocks is tricky since the server does not know how big the world is. In the worst case it only returns blocks for already loaded chunks or you need to specify a area to search in. Please specify the API request.

**Comment by Janmm14** [comment]
- [ ] i18n Befehlsbeschreibungen
- [ ] EntityLiving#getEffectDurationRemaining(TimeUnit)

**Comment by Goodstuff4UonYT** [comment]
https://trello.com/b/O2sNXl6c/issues-requests

**Comment by geNAZt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pmmp worlds / nukkit worlds are broken](https://trello.com/c/SeYaPjHK/3-pmmp-worlds-nukkit-worlds-are-broken)
