### ISSUE TITLE
List of Bugs

### ISSUE THREAD

**Issue by Ali1v** [gomint/gomint#549]
***This is a new list of bugs that need to be fixed for GoMint to become stable***😊

**Blocks**
- [x] When a grass block is destroyed, the grass is not destroyed and remains in the air
- [x] Mob heads cannot be placed

- [x] Can't place redstone dust
- [x] Breaking leaves does not drop saplings
- [x] 2 chest next to each other do not become one big chest
- [x] Wooden buttons can be removed too quickly by hand
- [x] Breaking floating ice doesn't spawn water
- [x] Blocks that should fall don't fall
- [x] Minecarts dont work
- [x] When the couldron is placed, it automatically contains water
- [x] Placing a lava source block inside a water source block doesn't make obsidian, it replacing the water block
- [x] When placing TNT, a completely different weird TNT comes with a different color
![Minecraft 13 08 2020 20_11_07](https://user-images.githubusercontent.com/53354661/90175668-0963c880-dda8-11ea-8e0e-9adea88fa759.png)
- [x] Walls don't connect ![unknown-16.png](https://user-images.githubusercontent.com/53354661/90983292-43358b80-e56d-11ea-915a-75090b600ed8.png)
- [x] BlackStoneStep Bug (see video)
https://tenor.com/view/gif-18207789
- [x] Netherwarts & Saplings can be placed on top of each other #448 ![unknown-11.png](https://user-images.githubusercontent.com/53354661/91352033-8865f180-e7e9-11ea-9f0f-fee4bd669d64.png)
- [ ] Block rotation is messed up
    - [x] Stairs
    - [x] Walls
    - [x] Torchs
    - [x] Doors
    - [ ] Trap doors
    - [ ] Fence Gates
    - [ ] Wooden steps
    - [ ] Logs
- [X] After doors are "destroyed" they become invisible and are still there
- [ ] Blockstates is messed up
    - [x] Pumpkins
    - [x] Scaffolding
    - [ ] Glass
    - [ ] Walls
    - [X] Planks
    - [ ] Glass panes 
    - [ ]  Shulker boxes
    - [ ]  Stone steps
    - [X] Banners
    - [ ] Boards

**Gameplay**
- [x] ~~Quick Craft bug(only happening in crafting tables)~~
- [x] ~~Tools don't break~~
- [x] ~~There is no dead screen~~

**Entitys / Players**
- [ ] Players can't sleep in a bed
- [x] ~~When you destroy Chest , black spots appear on the floor~~
- [x] ~~If you place a chest block on grass, the grass becomes a (fake) chest~~
 ![20200807_233444.gif](https://user-images.githubusercontent.com/53354661/89690779-a08fd280-d907-11ea-9d1f-75730e336f0d.gif)
- [x] Player inventory isn't saved when leaving the server(#259) 

- [ ] Players take too much damage from drowning
- [ ] No fall damage Sound 
- [ ] Players still burn after they die
- [ ] Arrows seem slightly laggy when in the air
- [ ] When starving, the player does not lose any damage
- [x] Hunger depletes too fast

**Items**
- [ ] When using Flint and Steel at TNT, the Flint and Steel disappears.
- [ ] Using flint and steel, light a liquid block on fire and it replaces the liquid with the fire block
- [ ] Items that are in the water cannot be picked up
- [ ] Placing water or lava from a bucket doesn't remove the water or lava from the bucke
- [x] Enchanted apples and golden apples give no effects
- [ ] Cannot use bone meal to grow saplings #473 

**World**
- [ ] No day / night cycle
- [ ] Water doesn't destroy plants
- [ ] Trees don't grow
- [ ] Plants don't grow

**Other**
- [ ] Fireworks don't propel an elytra forward
- [ ] Oxygen bar when underwater in creative shows
- [x] API Docs are offline(#548)
- [x] Sometimes players cannot connect to the server

**Comment by geNAZt** [comment]
Can you give an example on how to use "Quick craft"? Crafting with the book for example should work. Which vanilla feature are you referring to here?

**Comment by Ali1v** [comment]
> Can you give an example on how to use "Quick craft"? Crafting with the book for example should work. Which vanilla feature are you referring to here?

@geNAZt In vanilla minecraft In the crafting book you can directly create an item with a right click, but if you do that in Gomint, the recipes are removed from the respective item and you get nothing.

**Comment by geNAZt** [comment]
Ok this is partly affected, on 2x2 crafting it works as expected, crafting tables are bugged. I will change that in the list above

**Comment by rjworks** [comment]
this sure will take more than a day to do.

**Comment by rjworks** [comment]
when you to tap a fire to put it out, it doesn’t go out
