### ISSUE TITLE
List of non implemented Features

### ISSUE THREAD

**Issue by Ali1v** [gomint/gomint#654]
***This is a new list of non implemented features ***😊

**Blocks**
- [ ] Not all block functions arent implemented
    - [ ] Anvils arent implemented 
    - [ ] Beacons arent implemented 
    - [ ] Respawn Anchors arent implemented 
    - [ ] Campfires arent implemented 
    - [ ] Smithing tables arent implemented 
    - [ ] Opens arent implemented 
    - [ ] Smokers arent implemented 
    - [ ] Cartography tables arent implemented 
    - [ ] Lecterns arent implemented 
    - [ ] Barrels arent implemented 
    - [ ] Composters arent implemented 
    - [ ] Blast furnaces arent implemented 
    - [ ] Stonecutters arent implemented 
    - [ ] Couldrons arent implemented 
    - [ ] Looms arent implemented 
    - [x] Grindstones arent implemented 
    - [ ] Brewing stands arent implemented 
    - [ ] Enderchests are not working properly
    - [ ] Spawners arent implemented 
    - [ ] Scaffolding is not implemented 
    - [ ] Command blocks arent implemented

**Gameplay**
- [ ] Achievements arent implemented 
- [ ] Trading System isnt implemented

**Entitys / Players**
- [ ] Mobs(AI)  just aren't implemented at all
- [ ] Armor Stands arent implemented 
- [ ] Ender Crystals arent implemented 

**Items**
- [ ] Totems arent implemented
- [ ] Tridents arent implemented 
- [ ] Hoes doesn't make a sound

- [ ] Spawn eggs arent implemented  
- [ ] Fireworks arent implemented
 

**World (Generation)**
- [ ] Dimensions arent implemented 
- [x] Vanilla Generation is not implemented 

**Other**
- [ ] Redstone is not implemented
- [ ] Not all vanilla commands are implemented
- [ ] Resource packs / behaviour packs arent implemented(#594)
- [ ] Enchaments arent implemented(#98)
- [ ] (Splash) Potions arent implemented(#100)
